import type { Rider } from "@goshats/types";
import { Timestamp } from "firebase/firestore";

/**
 * Generate mock riders around a center point for testing.
 * Offsets are small so riders appear nearby on the map.
 */
export function createMockRiders(
  centerLat: number,
  centerLng: number,
): Rider[] {
  const now = Timestamp.now();

  return [
    {
      uid: "mock-rider-1",
      surname: "Adeyemi",
      otherName: "Tunde",
      email: "tunde@example.com",
      phone: "+2348012345678",
      profilePhotoUrl: null,
      vehicleType: "motorcycle",
      vehiclePlate: "ABJ-234KL",
      vehicleModel: "Bajaj Boxer",
      vehicleColor: "Red",
      vehicleYear: 2022,
      currentLocation: {
        latitude: centerLat + 0.003,
        longitude: centerLng - 0.002,
      },
      geohash: "s1234",
      isOnline: true,
      isAvailable: true,
      status: "approved",
      tier: "standard",
      totalTrips: 142,
      totalEarningsKobo: 450000,
      pendingEarningsKobo: 12000,
      averageRating: 4.6,
      totalRatings: 98,
      fcmTokens: [],
      createdAt: now,
      updatedAt: now,
    },
    {
      uid: "mock-rider-2",
      surname: "Ibrahim",
      otherName: "Musa",
      email: "musa@example.com",
      phone: "+2348098765432",
      profilePhotoUrl: null,
      vehicleType: "car",
      vehiclePlate: "ABJ-891TY",
      vehicleModel: "Toyota Corolla",
      vehicleColor: "Silver",
      vehicleYear: 2020,
      currentLocation: {
        latitude: centerLat - 0.004,
        longitude: centerLng + 0.003,
      },
      geohash: "s1234",
      isOnline: true,
      isAvailable: true,
      status: "approved",
      tier: "premium",
      totalTrips: 387,
      totalEarningsKobo: 1250000,
      pendingEarningsKobo: 35000,
      averageRating: 4.9,
      totalRatings: 310,
      fcmTokens: [],
      createdAt: now,
      updatedAt: now,
    },
    {
      uid: "mock-rider-3",
      surname: "Okafor",
      otherName: "Chidi",
      email: "chidi@example.com",
      phone: "+2348055512345",
      profilePhotoUrl: null,
      vehicleType: "bicycle",
      vehiclePlate: "N/A",
      vehicleModel: "Trek FX",
      vehicleColor: "Blue",
      vehicleYear: 2023,
      currentLocation: {
        latitude: centerLat + 0.002,
        longitude: centerLng + 0.004,
      },
      geohash: "s1234",
      isOnline: true,
      isAvailable: true,
      status: "approved",
      tier: "standard",
      totalTrips: 56,
      totalEarningsKobo: 180000,
      pendingEarningsKobo: 8000,
      averageRating: 4.3,
      totalRatings: 41,
      fcmTokens: [],
      createdAt: now,
      updatedAt: now,
    },
    {
      uid: "mock-rider-4",
      surname: "Bello",
      otherName: "Amina",
      email: "amina@example.com",
      phone: "+2348077788899",
      profilePhotoUrl: null,
      vehicleType: "motorcycle",
      vehiclePlate: "ABJ-567MN",
      vehicleModel: "Honda CG125",
      vehicleColor: "Black",
      vehicleYear: 2021,
      currentLocation: {
        latitude: centerLat - 0.002,
        longitude: centerLng - 0.003,
      },
      geohash: "s1234",
      isOnline: true,
      isAvailable: true,
      status: "approved",
      tier: "express",
      totalTrips: 612,
      totalEarningsKobo: 2100000,
      pendingEarningsKobo: 52000,
      averageRating: 4.8,
      totalRatings: 489,
      fcmTokens: [],
      createdAt: now,
      updatedAt: now,
    },
    {
      uid: "mock-rider-5",
      surname: "Eze",
      otherName: "Kalu",
      email: "kalu@example.com",
      phone: "+2348033344455",
      profilePhotoUrl: null,
      vehicleType: "van",
      vehiclePlate: "ABJ-012QR",
      vehicleModel: "Hiace Bus",
      vehicleColor: "White",
      vehicleYear: 2019,
      currentLocation: {
        latitude: centerLat + 0.005,
        longitude: centerLng + 0.001,
      },
      geohash: "s1234",
      isOnline: true,
      isAvailable: true,
      status: "approved",
      tier: "premium",
      totalTrips: 203,
      totalEarningsKobo: 890000,
      pendingEarningsKobo: 22000,
      averageRating: 4.5,
      totalRatings: 167,
      fcmTokens: [],
      createdAt: now,
      updatedAt: now,
    },
  ];
}
