import type { Order } from "@goshats/types";
import { Timestamp } from "firebase/firestore";

const now = new Date();
const yesterday = new Date(now.getTime() - 86400000);

export const MOCK_ORDERS: Order[] = [
  {
    id: "mock-1",
    customer: { id: "c1", name: "Alice", phone: "+2348000000001", avatarUrl: null },
    driver: { id: "d1", name: "Rider", phone: "+2348000000002", vehiclePlate: "ABC-123" },
    pickup: {
      address: "14a Adetokunbo Ademola Street, Victoria Island",
      location: { latitude: 6.4281, longitude: 3.4219 },
      contactName: "Bukka Hut",
      contactPhone: "08012345678",
    },
    dropoff: {
      address: "Lekki Phase 1, Admiralty Way",
      location: { latitude: 6.4474, longitude: 3.4723 },
      contactName: "Alice",
      contactPhone: "08012345678",
    },
    fareAmountKobo: 250000,
    tipAmountKobo: 50000,
    totalAmountKobo: 300000,
    status: "delivered",
    loadType: "food",
    isHighValue: false,
    loadDescription: "Two plates of Jollof rice and plantain",
    createdAt: Timestamp.fromDate(now),
    updatedAt: Timestamp.fromDate(now),
    timeline: [
      { status: "pending", timestamp: Timestamp.fromDate(new Date(now.getTime() - 3600000)) },
      { status: "accepted", timestamp: Timestamp.fromDate(new Date(now.getTime() - 3500000)) },
      { status: "arrived_pickup", timestamp: Timestamp.fromDate(new Date(now.getTime() - 2500000)) },
      { status: "picked_up", timestamp: Timestamp.fromDate(new Date(now.getTime() - 2400000)) },
      { status: "in_transit", timestamp: Timestamp.fromDate(new Date(now.getTime() - 2000000)) },
      { status: "delivered", timestamp: Timestamp.fromDate(now), note: "Left at front door" },
    ],
  } as unknown as Order,
  {
    id: "mock-2",
    customer: { id: "c2", name: "Bob", phone: "+2348000000003", avatarUrl: null },
    driver: null,
    pickup: {
      address: "Computer Village, Ikeja",
      location: { latitude: 6.5965, longitude: 3.3421 },
      contactName: "Tech Store",
      contactPhone: "08023456789",
    },
    dropoff: {
      address: "Maryland Mall",
      location: { latitude: 6.5764, longitude: 3.3653 },
      contactName: "Bob",
      contactPhone: "08023456789",
    },
    fareAmountKobo: 450000,
    tipAmountKobo: 0,
    totalAmountKobo: 450000,
    status: "in_transit",
    loadType: "parcel",
    isHighValue: true,
    loadDescription: "MacBook Pro M3",
    createdAt: Timestamp.fromDate(now),
    updatedAt: Timestamp.fromDate(now),
    timeline: [
      { status: "pending", timestamp: Timestamp.fromDate(new Date(now.getTime() - 1800000)) },
      { status: "accepted", timestamp: Timestamp.fromDate(new Date(now.getTime() - 1700000)) },
      { status: "arrived_pickup", timestamp: Timestamp.fromDate(new Date(now.getTime() - 1000000)) },
      { status: "picked_up", timestamp: Timestamp.fromDate(new Date(now.getTime() - 900000)) },
      { status: "in_transit", timestamp: Timestamp.fromDate(new Date(now.getTime() - 100000)) },
    ],
  } as unknown as Order,
  {
    id: "mock-3",
    customer: { id: "c3", name: "Charlie", phone: "+2348000000004", avatarUrl: null },
    driver: { id: "d1", name: "Rider", phone: "+2348000000002", vehiclePlate: "ABC-123" },
    pickup: {
      address: "Yaba Tech",
      location: { latitude: 6.5178, longitude: 3.3725 },
      contactName: "Registry",
      contactPhone: "08034567890",
    },
    dropoff: {
      address: "Surulere",
      location: { latitude: 6.4961, longitude: 3.3524 },
      contactName: "Charlie",
      contactPhone: "08034567890",
    },
    fareAmountKobo: 120000,
    tipAmountKobo: 20000,
    totalAmountKobo: 140000,
    status: "delivered",
    loadType: "document",
    isHighValue: false,
    loadDescription: "Official Transcripts",
    createdAt: Timestamp.fromDate(yesterday),
    updatedAt: Timestamp.fromDate(yesterday),
    timeline: [
      { status: "pending", timestamp: Timestamp.fromDate(new Date(yesterday.getTime() - 3600000)) },
      { status: "accepted", timestamp: Timestamp.fromDate(new Date(yesterday.getTime() - 3500000)) },
      { status: "arrived_pickup", timestamp: Timestamp.fromDate(new Date(yesterday.getTime() - 2500000)) },
      { status: "picked_up", timestamp: Timestamp.fromDate(new Date(yesterday.getTime() - 2400000)) },
      { status: "in_transit", timestamp: Timestamp.fromDate(new Date(yesterday.getTime() - 2000000)) },
      { status: "delivered", timestamp: Timestamp.fromDate(yesterday), note: "Hand delivered" },
    ],
  } as unknown as Order,
];
